import {
  makeAnyLayoutFilter,
  makeArtistFilter,
  makeArtistNoteFilter,
  makeBannedFilter,
  makeBlockFilter,
  makeBorderFilter,
  makeCardFrameFilter,
  makeCardLayoutFilter,
  makeCardtypeFilter,
  makeCollectorNumberFilter,
  makeColorFilter,
  makeCostFilter,
  makeCreatorFilter,
  makeDefenseFilter,
  makeFaceLayoutFilter,
  makeFlavorFilter,
  makeFrameEffectFilter,
  makeFrameFilter,
  makeGroupFilter,
  makeHasFilter,
  makeHasRelatedFilter,
  makeHybridFilter,
  makeIdentityFilter,
  makeIDFilter,
  makeIncludeFilter,
  makeIndicatorFilter,
  makeInFilter,
  makeInvalidColorFilter,
  makeInvalidFilter,
  makeInvalidKeywordFilter,
  makeInvalidSortFilter,
  makeIsFilter,
  makeIsRelatedFilter,
  makeKeywordFilter,
  makeKindFilter,
  makeLegalFilter,
  makeLoreFilter,
  makeLoyaltyFilter,
  makeManaValueFilter,
  makeMiscColorFilter,
  makeMiscHybridFilter,
  makeMiscIdentityFilter,
  makeMiscIndicatorFilter,
  makeNameFilter,
  makeNotLegalFilter,
  makeOracleFilter,
  makeOracleIDFilter,
  makePowerFilter,
  makePrintsNumberFilter,
  makePTFilter,
  makeRulingFilter,
  makeSetFilter,
  makeSetsNumberFilter,
  makeSetTypeFilter,
  makeShowcaseFilter,
  makeSubtypeFilter,
  makeSupertypeFilter,
  makeTagFilter,
  makeTagNoteFilter,
  makeToughnessFilter,
  makeTypeFilter,
  makeWatermarkFilter,
} from '../makers';
import { colorFilterMaker, filterMaker, stateFilterMaker } from '../types';

export const filterNames = [
  'id',
  'oracleid',
  'kind',
  'name',
  'set',
  'block',
  'group',
  'settype',
  'number',
  'layout',
  'facelayout',
  'anylayout',
  'mana',
  'manavalue',
  'supertype',
  'cardtype',
  'subtype',
  'type',
  'oracle',
  'flavor',
  'lore',
  'power',
  'toughness',
  'pt',
  'loyalty',
  'defense',
  'keyword',
  'legal',
  'notlegal',
  'banned',
  'creator',
  'artist',
  'artistnote',
  'ruling',
  'watermark',
  'border',
  'cardframe',
  'frameeffect',
  'frame',
  'showcase',
  'tag',
  'tagnote',
  'isrelated',
  'hasrelated',
  'include',
  'invalid',
  'invalidsort',
  'invalidkeyword',
  'invalidcolor',
] as const;
export type filterNameType = (typeof filterNames)[number];

export const equivFilterNames: Record<string, filterNameType> = {
  cardid: 'id',
  hcid: 'id',
  oid: 'oracleid',
  oi: 'oracleid',
  k: 'kind',
  n: 'name',
  s: 'set',
  b: 'block',
  g: 'group',
  st: 'settype',
  cube: 'settype',
  cn: 'number',
  collector: 'number',
  collectornumber: 'number',
  cardlayout: 'layout',
  fl: 'facelayout',
  al: 'anylayout',
  m: 'mana',
  cost: 'mana',
  manacost: 'mana',
  mv: 'manavalue',
  cmc: 'manavalue',
  t: 'type',
  super: 'supertype',
  supert: 'supertype',
  ct: 'cardtype',
  ctype: 'cardtype',
  sub: 'subtype',
  subt: 'subtype',
  o: 'oracle',
  text: 'oracle',
  oracletext: 'oracle',
  rules: 'oracle',
  rulestext: 'oracle',
  ft: 'flavor',
  flavortext: 'flavor',
  pow: 'power',
  tou: 'toughness',
  powtou: 'pt',
  tough: 'toughness',
  loy: 'loyalty',
  def: 'defense',
  kw: 'keyword',
  keywords: 'keyword',
  f: 'legal',
  format: 'legal',
  creators: 'creator',
  a: 'artist',
  artists: 'artist',
  an: 'artistnote',
  anote: 'artistnote',
  ans: 'artistnote',
  anotes: 'artistnote',
  artistn: 'artistnote',
  artistns: 'artistnote',
  artistnotes: 'artistnote',
  rulings: 'ruling',
  bordercolor: 'border',
  wm: 'watermark',
  watermarks: 'watermark',
  frameeffects: 'frameeffect',
  fe: 'frameeffect',
  show: 'showcase',
  sc: 'showcase',
  otag: 'tag',
  oracletag: 'tag',
  function: 'tag',
  tn: 'tagnote',
  tnote: 'tagnote',
  tns: 'tagnote',
  tnotes: 'tagnote',
  tagn: 'tagnote',
  tagns: 'tagnote',
  tagnotes: 'tagnote',
  ir: 'isrelated',
  isrel: 'isrelated',
  isrels: 'isrelated',
  isrelateds: 'isrelated',
  hr: 'hasrelated',
  rel: 'hasrelated',
  rels: 'hasrelated',
  hasrel: 'hasrelated',
  hasrels: 'hasrelated',
  related: 'hasrelated',
  relateds: 'hasrelated',
  hasrelateds: 'hasrelated',
  sort: 'invalidsort',
  order: 'invalidsort',
  dir: 'invalidsort',
  direction: 'invalidsort',
};

export const filters: Record<filterNameType, filterMaker> = {
  id: makeIDFilter,
  oracleid: makeOracleIDFilter,
  kind: makeKindFilter,
  name: makeNameFilter,
  set: makeSetFilter,
  block: makeBlockFilter,
  group: makeGroupFilter,
  settype: makeSetTypeFilter,
  number: makeCollectorNumberFilter,
  layout: makeCardLayoutFilter,
  facelayout: makeFaceLayoutFilter,
  anylayout: makeAnyLayoutFilter,
  mana: makeCostFilter,
  manavalue: makeManaValueFilter,
  supertype: makeSupertypeFilter,
  cardtype: makeCardtypeFilter,
  subtype: makeSubtypeFilter,
  type: makeTypeFilter,
  oracle: makeOracleFilter,
  flavor: makeFlavorFilter,
  lore: makeLoreFilter,
  power: makePowerFilter,
  toughness: makeToughnessFilter,
  pt: makePTFilter,
  loyalty: makeLoyaltyFilter,
  defense: makeDefenseFilter,
  keyword: makeKeywordFilter,
  legal: makeLegalFilter,
  notlegal: makeNotLegalFilter,
  banned: makeBannedFilter,
  creator: makeCreatorFilter,
  artist: makeArtistFilter,
  artistnote: makeArtistNoteFilter,
  ruling: makeRulingFilter,
  watermark: makeWatermarkFilter,
  border: makeBorderFilter,
  cardframe: makeCardFrameFilter,
  frameeffect: makeFrameEffectFilter,
  frame: makeFrameFilter,
  showcase: makeShowcaseFilter,
  tag: makeTagFilter,
  tagnote: makeTagNoteFilter,
  isrelated: makeIsRelatedFilter,
  hasrelated: makeHasRelatedFilter,
  invalid: makeInvalidFilter,
  invalidsort: makeInvalidSortFilter,
  invalidkeyword: makeInvalidKeywordFilter,
  invalidcolor: makeInvalidColorFilter,
  include: makeIncludeFilter,
};

const colorFilterNames = [
  'color',
  'indicator',
  'identity',
  'hybrid',
  'misccolor',
  'miscindicator',
  'miscidentity',
  'mischybrid',
] as const;
export type colorFilterNameType = (typeof colorFilterNames)[number];

export const equivColorFilterNames: Record<string, colorFilterNameType> = {
  c: 'color',
  colors: 'color',
  colorindicator: 'indicator',
  ci: 'identity',
  cidentity: 'identity',
  colorid: 'identity',
  cid: 'identity',
  hi: 'hybrid',
  hci: 'hybrid',
  hid: 'hybrid',
  hcid: 'hybrid',
  hybridid: 'hybrid',
  hybrididentity: 'hybrid',
  hybridcoloridentity: 'hybrid',
  mc: 'misccolor',
  mcolors: 'misccolor',
  mcolorindicator: 'miscindicator',
  mci: 'miscidentity',
  mcidentity: 'miscidentity',
  mcolorid: 'miscidentity',
  mcid: 'miscidentity',
  mhi: 'mischybrid',
  mhci: 'mischybrid',
  mhid: 'mischybrid',
  mhcid: 'mischybrid',
  mhybridid: 'mischybrid',
  mhybrididentity: 'mischybrid',
  mhybridcoloridentity: 'mischybrid',
  miscc: 'misccolor',
  misccolors: 'misccolor',
  misccolorindicator: 'miscindicator',
  miscci: 'miscidentity',
  misccidentity: 'miscidentity',
  misccolorid: 'miscidentity',
  misccid: 'miscidentity',
  mischi: 'mischybrid',
  mischci: 'mischybrid',
  mischid: 'mischybrid',
  mischcid: 'mischybrid',
  mischybridid: 'mischybrid',
  mischybrididentity: 'mischybrid',
  mischybridcoloridentity: 'mischybrid',
};
export const colorFilters: Record<colorFilterNameType, colorFilterMaker> = {
  color: makeColorFilter,
  indicator: makeIndicatorFilter,
  identity: makeIdentityFilter,
  hybrid: makeHybridFilter,
  misccolor: makeMiscColorFilter,
  miscindicator: makeMiscIndicatorFilter,
  miscidentity: makeMiscIdentityFilter,
  mischybrid: makeMiscHybridFilter,
};

const printsFilterNames = ['in', 'sets', 'prints', 'is', 'has'] as const;
export type printsFilterNameType = (typeof printsFilterNames)[number];

export const equivPrintsFilterNames: Record<string, printsFilterNameType> = {};
export const printsFilters: Record<printsFilterNameType, stateFilterMaker> = {
  in: makeInFilter,
  sets: makeSetsNumberFilter,
  prints: makePrintsNumberFilter,
  is: makeIsFilter,
  has: makeHasFilter,
};

export const invertedFilterNames: Record<string, filterNameType | printsFilterNameType> = {
  not: 'is',
  exclude: 'include',
};
