import {
  makeAnyLayoutFilter,
  makeArtistFilter,
  makeArtistNoteFilter,
  makeBannedFilter,
  makeBlockFilter,
  makeBorderFilter,
  makeCardFrameFilter,
  makeCardLayoutFilter,
  makeCardtypeFilter,
  makeCollectorNumberFilter,
  makeColorFilter,
  makeCostFilter,
  makeCreatorFilter,
  makeDefenseFilter,
  makeFaceLayoutFilter,
  makeFlavorFilter,
  makeFrameEffectFilter,
  makeFrameFilter,
  makeGroupFilter,
  makeHasFilter,
  makeHasRelatedFilter,
  makeHybridFilter,
  makeIdentityFilter,
  makeIDFilter,
  makeIncludeFilter,
  makeIndicatorFilter,
  makeInFilter,
  makeInvalidColorFilter,
  makeInvalidFilter,
  makeInvalidKeywordFilter,
  makeInvalidSortFilter,
  makeIsFilter,
  makeIsRelatedFilter,
  makeKeywordFilter,
  makeKindFilter,
  makeLegalFilter,
  makeLoreFilter,
  makeLoyaltyFilter,
  makeManaValueFilter,
  makeMiscColorFilter,
  makeMiscHybridFilter,
  makeMiscIdentityFilter,
  makeMiscIndicatorFilter,
  makeNameFilter,
  makeNotLegalFilter,
  makeOracleFilter,
  makeOracleIDFilter,
  makePowerFilter,
  makePrintsNumberFilter,
  makePTFilter,
  makeRulingFilter,
  makeSetFilter,
  makeSetsNumberFilter,
  makeSetTypeFilter,
  makeShowcaseFilter,
  makeSubtypeFilter,
  makeSupertypeFilter,
  makeTagFilter,
  makeTagNoteFilter,
  makeToughnessFilter,
  makeTypeFilter,
  makeWatermarkFilter,
} from '../makers';
import {
  colorFilterMaker,
  filterMaker,
  stateFilterMaker,
  colorFilterNameType,
  filterNameType,
  printsFilterNameType,
} from '../types';

export const filters: Record<filterNameType, filterMaker> = {
  id: makeIDFilter,
  oracleid: makeOracleIDFilter,
  kind: makeKindFilter,
  name: makeNameFilter,
  set: makeSetFilter,
  block: makeBlockFilter,
  group: makeGroupFilter,
  settype: makeSetTypeFilter,
  number: makeCollectorNumberFilter,
  layout: makeCardLayoutFilter,
  facelayout: makeFaceLayoutFilter,
  anylayout: makeAnyLayoutFilter,
  mana: makeCostFilter,
  manavalue: makeManaValueFilter,
  supertype: makeSupertypeFilter,
  cardtype: makeCardtypeFilter,
  subtype: makeSubtypeFilter,
  type: makeTypeFilter,
  oracle: makeOracleFilter,
  flavor: makeFlavorFilter,
  lore: makeLoreFilter,
  power: makePowerFilter,
  toughness: makeToughnessFilter,
  pt: makePTFilter,
  loyalty: makeLoyaltyFilter,
  defense: makeDefenseFilter,
  keyword: makeKeywordFilter,
  legal: makeLegalFilter,
  notlegal: makeNotLegalFilter,
  banned: makeBannedFilter,
  creator: makeCreatorFilter,
  artist: makeArtistFilter,
  artistnote: makeArtistNoteFilter,
  ruling: makeRulingFilter,
  watermark: makeWatermarkFilter,
  border: makeBorderFilter,
  cardframe: makeCardFrameFilter,
  frameeffect: makeFrameEffectFilter,
  frame: makeFrameFilter,
  showcase: makeShowcaseFilter,
  tag: makeTagFilter,
  tagnote: makeTagNoteFilter,
  isrelated: makeIsRelatedFilter,
  hasrelated: makeHasRelatedFilter,
  invalid: makeInvalidFilter,
  invalidsort: makeInvalidSortFilter,
  invalidkeyword: makeInvalidKeywordFilter,
  invalidcolor: makeInvalidColorFilter,
  include: makeIncludeFilter,
};

export const colorFilters: Record<colorFilterNameType, colorFilterMaker> = {
  color: makeColorFilter,
  indicator: makeIndicatorFilter,
  identity: makeIdentityFilter,
  hybrid: makeHybridFilter,
  misccolor: makeMiscColorFilter,
  miscindicator: makeMiscIndicatorFilter,
  miscidentity: makeMiscIdentityFilter,
  mischybrid: makeMiscHybridFilter,
};

export const printsFilters: Record<printsFilterNameType, stateFilterMaker> = {
  in: makeInFilter,
  sets: makeSetsNumberFilter,
  prints: makePrintsNumberFilter,
  is: makeIsFilter,
  has: makeHasFilter,
};
