import { HCCard, HCFrame, HCFrameEffect } from '@hellfall/shared/types';
import { cardStringFilter, getActualOp, looseOpType, opType, shareOp } from '../types';
const toCardFrame: Record<string, HCFrame | HCFrame[]> = {
  '1993': HCFrame.Original,
  '93': HCFrame.Original,
  "'93": HCFrame.Original,
  original: HCFrame.Original,
  '1997': [HCFrame.Classic, HCFrame.ClassicToken],
  '97': [HCFrame.Classic, HCFrame.ClassicToken],
  "'97": [HCFrame.Classic, HCFrame.ClassicToken],
  classic: [HCFrame.Classic, HCFrame.ClassicToken],
  '1997card': HCFrame.Classic,
  '97card': HCFrame.Classic,
  "'97card": HCFrame.Classic,
  classiccard: HCFrame.Classic,
  '1997token': HCFrame.ClassicToken,
  '97token': HCFrame.ClassicToken,
  "'97token": HCFrame.ClassicToken,
  classictoken: HCFrame.ClassicToken,
  retro: [HCFrame.Original, HCFrame.Classic, HCFrame.ClassicToken],
  old: [HCFrame.Original, HCFrame.Classic, HCFrame.ClassicToken],
  retrocard: [HCFrame.Original, HCFrame.Classic],
  oldcard: [HCFrame.Original, HCFrame.Classic],
  retrotoken: HCFrame.ClassicToken,
  oldtoken: HCFrame.ClassicToken,
  '2003': [HCFrame.Modern, HCFrame.ModernToken],
  '03': [HCFrame.Modern, HCFrame.ModernToken],
  "'03": [HCFrame.Modern, HCFrame.ModernToken],
  modern: [HCFrame.Modern, HCFrame.ModernToken],
  '2003card': HCFrame.Modern,
  '03card': HCFrame.Modern,
  "'03card": HCFrame.Modern,
  moderncard: HCFrame.Modern,
  '2003token': HCFrame.ModernToken,
  '03token': HCFrame.ModernToken,
  "'03token": HCFrame.ModernToken,
  moderntoken: HCFrame.ModernToken,
  '2015': [HCFrame.Stamp, HCFrame.StampToken],
  '15': [HCFrame.Stamp, HCFrame.StampToken],
  "'15": [HCFrame.Stamp, HCFrame.StampToken],
  stamp: [HCFrame.Stamp, HCFrame.StampToken],
  '2015card': HCFrame.Stamp,
  '15card': HCFrame.Stamp,
  "'15card": HCFrame.Stamp,
  stampcard: HCFrame.Stamp,
  '2015token': HCFrame.StampToken,
  '15token': HCFrame.StampToken,
  "'15token": HCFrame.StampToken,
  stamptoken: HCFrame.StampToken,
  '2020': HCFrame.FullToken,
  '20': HCFrame.FullToken,
  "'20": HCFrame.FullToken,
  full: HCFrame.FullToken,
  '2020token': HCFrame.FullToken,
  '20token': HCFrame.FullToken,
  "'20token": HCFrame.FullToken,
  fulltoken: HCFrame.FullToken,
  future: HCFrame.Future,
  playtest: HCFrame.Playtest,
  shattered: HCFrame.Shattered,
  new: [
    HCFrame.Modern,
    HCFrame.Stamp,
    HCFrame.Future,
    HCFrame.Playtest,
    HCFrame.Shattered,
    HCFrame.ModernToken,
    HCFrame.StampToken,
    HCFrame.FullToken,
  ],
  card: [
    HCFrame.Original,
    HCFrame.Classic,
    HCFrame.Modern,
    HCFrame.Stamp,
    HCFrame.Future,
    HCFrame.Playtest,
    HCFrame.Shattered,
  ],
  anycard: [
    HCFrame.Original,
    HCFrame.Classic,
    HCFrame.Modern,
    HCFrame.Stamp,
    HCFrame.Future,
    HCFrame.Playtest,
    HCFrame.Shattered,
  ],
  token: [HCFrame.ClassicToken, HCFrame.ModernToken, HCFrame.StampToken, HCFrame.FullToken],
  anytoken: [HCFrame.ClassicToken, HCFrame.ModernToken, HCFrame.StampToken, HCFrame.FullToken],
  magic: [
    HCFrame.Original,
    HCFrame.Classic,
    HCFrame.Modern,
    HCFrame.Stamp,
    HCFrame.Future,
    HCFrame.Playtest,
    HCFrame.Shattered,
    HCFrame.ClassicToken,
    HCFrame.ModernToken,
    HCFrame.StampToken,
    HCFrame.FullToken,
  ],
  jank: HCFrame.Jank,
  notmagic: HCFrame.NotMagic,
  nonmagic: HCFrame.NotMagic,
  pokemon: HCFrame.Pokemon,
  yugioh: HCFrame.Yugioh,
  legendsofruneterra: HCFrame.LegendsOfRuneterra,
  lor: HCFrame.LegendsOfRuneterra,
  runeterra: HCFrame.LegendsOfRuneterra,
  slaythespire: HCFrame.SlayTheSpire,
  inscryption: HCFrame.Inscryption,
  hearthstone: HCFrame.Hearthstone,
  lorcana: HCFrame.Lorcana,
  anynotmagic: [
    HCFrame.NotMagic,
    HCFrame.Pokemon,
    HCFrame.Yugioh,
    HCFrame.LegendsOfRuneterra,
    HCFrame.SlayTheSpire,
    HCFrame.Inscryption,
    HCFrame.Hearthstone,
    HCFrame.Lorcana,
  ],
  anynonmagic: [
    HCFrame.NotMagic,
    HCFrame.Pokemon,
    HCFrame.Yugioh,
    HCFrame.LegendsOfRuneterra,
    HCFrame.SlayTheSpire,
    HCFrame.Inscryption,
    HCFrame.Hearthstone,
    HCFrame.Lorcana,
  ],
  websiteapp: HCFrame.WebsiteApp,
  website: HCFrame.WebsiteApp,
  app: HCFrame.WebsiteApp,
};
const toFrameEffect: Record<string, HCFrameEffect | HCFrameEffect[]> = {
  sunmoondfc: HCFrameEffect.SunMoonDfc,
  sunmoontransform: HCFrameEffect.SunMoonDfc,
  sunmoon: HCFrameEffect.SunMoonDfc,
  sundfc: HCFrameEffect.SunMoonDfc,
  suntransform: HCFrameEffect.SunMoonDfc,
  sun: HCFrameEffect.SunMoonDfc,
  moontransform: [HCFrameEffect.SunMoonDfc, HCFrameEffect.MoonEldraziDfc],
  moondfc: [HCFrameEffect.SunMoonDfc, HCFrameEffect.MoonEldraziDfc],
  moon: [HCFrameEffect.SunMoonDfc, HCFrameEffect.MoonEldraziDfc],
  mooneldrazidfc: HCFrameEffect.MoonEldraziDfc,
  mooneldrazitransform: HCFrameEffect.MoonEldraziDfc,
  mooneldrazi: HCFrameEffect.MoonEldraziDfc,
  eldrazidfc: HCFrameEffect.MoonEldraziDfc,
  eldrazitransform: HCFrameEffect.MoonEldraziDfc,
  eldrazi: HCFrameEffect.MoonEldraziDfc,
  emrakuldfc: HCFrameEffect.MoonEldraziDfc,
  emrakultransform: HCFrameEffect.MoonEldraziDfc,
  emrakul: HCFrameEffect.MoonEldraziDfc,
  fandfc: HCFrameEffect.FanDfc,
  fantransform: HCFrameEffect.FanDfc,
  fan: HCFrameEffect.FanDfc,
  compasslanddfc: HCFrameEffect.CompassLandDfc,
  compasslandtransform: HCFrameEffect.CompassLandDfc,
  compassland: HCFrameEffect.CompassLandDfc,
  compassdfc: HCFrameEffect.CompassLandDfc,
  compasstransform: HCFrameEffect.CompassLandDfc,
  compass: HCFrameEffect.CompassLandDfc,
  landdfc: HCFrameEffect.CompassLandDfc,
  landtransform: HCFrameEffect.CompassLandDfc,
  land: HCFrameEffect.CompassLandDfc,
  originpwdfc: HCFrameEffect.OriginPwDfc,
  originpwtransform: HCFrameEffect.OriginPwDfc,
  originpw: HCFrameEffect.OriginPwDfc,
  origindfc: HCFrameEffect.OriginPwDfc,
  origintransform: HCFrameEffect.OriginPwDfc,
  origin: HCFrameEffect.OriginPwDfc,
  pwdfc: HCFrameEffect.OriginPwDfc,
  pwtransform: HCFrameEffect.OriginPwDfc,
  pw: HCFrameEffect.OriginPwDfc,
  typedfc: HCFrameEffect.TypeDfc,
  typetransform: HCFrameEffect.TypeDfc,
  type: HCFrameEffect.TypeDfc,
  transformdfc: HCFrameEffect.TransformDfc,
  transform: HCFrameEffect.TransformDfc,
  tdfc: HCFrameEffect.TransformDfc,
  modaldfc: HCFrameEffect.Mdfc,
  modal: HCFrameEffect.Mdfc,
  mdfc: HCFrameEffect.Mdfc,
  specialize: HCFrameEffect.Specialize,
  meld: HCFrameEffect.Meld,
  anytransform: [
    HCFrameEffect.SunMoonDfc,
    HCFrameEffect.CompassLandDfc,
    HCFrameEffect.OriginPwDfc,
    HCFrameEffect.MoonEldraziDfc,
    HCFrameEffect.FanDfc,
    HCFrameEffect.TypeDfc,
    HCFrameEffect.TransformDfc,
  ],
  anydfc: [
    HCFrameEffect.SunMoonDfc,
    HCFrameEffect.CompassLandDfc,
    HCFrameEffect.OriginPwDfc,
    HCFrameEffect.MoonEldraziDfc,
    HCFrameEffect.FanDfc,
    HCFrameEffect.TypeDfc,
    HCFrameEffect.TransformDfc,
    HCFrameEffect.Mdfc,
    HCFrameEffect.Specialize,
    HCFrameEffect.Meld,
  ],
  legendary: HCFrameEffect.Legendary,
  legend: HCFrameEffect.Legendary,
  companion: HCFrameEffect.Companion,
  snow: HCFrameEffect.Snow,
  enchantment: HCFrameEffect.Enchantment,
  nyx: HCFrameEffect.Enchantment,
  lesson: HCFrameEffect.Lesson,
  vehicle: HCFrameEffect.Vehicle,
  miracle: HCFrameEffect.Miracle,
  draft: HCFrameEffect.Draft,
  conspiracy: HCFrameEffect.Draft,
  devoid: HCFrameEffect.Devoid,
  spree: HCFrameEffect.Spree,
  tombstone: HCFrameEffect.Tombstone,
  colorshifted: HCFrameEffect.Colorshifted,
  colorshift: HCFrameEffect.Colorshifted,
  inverted: HCFrameEffect.Inverted,
  invertedtext: HCFrameEffect.Inverted,
  showcase: HCFrameEffect.Showcase,
  masterpiece: HCFrameEffect.Masterpiece,
  full: HCFrameEffect.FullArt,
  fullart: HCFrameEffect.FullArt,
  extended: HCFrameEffect.ExtendedArt,
  extendedart: HCFrameEffect.ExtendedArt,
  verticalart: HCFrameEffect.VerticalArt,
  vertical: HCFrameEffect.VerticalArt,
  noart: HCFrameEffect.NoArt,
  etched: HCFrameEffect.Etched,
  slab: HCFrameEffect.Slab,
  slabbed: HCFrameEffect.Slab,
  arena: HCFrameEffect.Arena,
};

const toShowcaseFrame: Record<string, string | string[]> = {
  kaladesh: 'Invention',
  invention: 'Invention',
  invocation: 'Invocation',
  amonkhet: 'Invocation',
  parchment: 'Parchment',
  storybook: 'Storybook',
  mural: 'Mural',
  eldraine: ['Storybook', 'Mural'],
  adventure: 'Storybook',
  signaturespellbook: 'Signature Spellbook',
  signature: 'Signature Spellbook',
  spellbook: 'Signature Spellbook',
  hedron: 'Hedron',
  landfall: 'Hedron',
  eldraziexpedition: 'Eldrazi Expedition',
  hedronexpedition: 'Hedron Expedition',
  expedition: ['Eldrazi Expedition', 'Hedron Expedition'],
  zendikar: ['Hedron', 'Eldrazi Expedition', 'Hedron Expedition'],
  phyrexian: 'Phyrexian',
  phyrexianized: 'Phyrexian',
  viking: 'Viking',
  kaldheim: 'Viking',
  strixhaven: 'Mystical Archive',
  mysticalarchive: 'Mystical Archive',
  mystical: 'Mystical Archive',
  archive: 'Mystical Archive',
  japanese: 'Japanese Mystical Archive',
  sketch: 'Sketch',
  module: 'Module',
  rulebook: 'Rulebook',
  dnd: ['Module', 'Rulebook'],
  equinox: 'Equinox',
  eternalnight: 'Eternal Night',
  doublefeature: 'Eternal Night',
  innistrad: ['Equinox', 'Eternal Night'],
  ninja: 'Ninja',
  samurai: 'Samurai',
  softglow: 'Soft Glow',
  kamigawa: ['Ninja', 'Samurai', 'Soft Glow'],
  goldenage: 'Golden Age',
  artdeco: 'Art Deco',
  skyscraper: 'Skyscraper',
  newcapenna: ['Golden Age', 'Art Deco', 'Skyscraper'],
  stainedglass: 'Stained Glass',
  thering: 'Ring',
  ring: 'Ring',
  scrolls: 'Scroll',
  scroll: 'Scroll',
  lotr: ['Ring', 'Scroll'],
  legendsofixalan: 'Legends of Ixalan',
  ixalan: ['Legends of Ixalan'],
  dossier: 'Dossier',
  magnified: 'Magnified',
  citymural: 'City',
  ravnica: ['Dossier', 'Magnified', 'City'],
  wanted: 'Wanted Poster',
  wantedposter: 'Wanted Poster',
  newspaper: 'Newspaper',
  bankvault: 'Vault',
  vault: 'Vault',
  thunderjunction: ['Wanted Poster', 'Newspaper', 'Bank Vault'],
  memorycorridor: 'Memory Corridor',
  critters: 'Critters',
  woodland: 'Woodland',
  bloomburrow: ['Critters', 'Woodland'],
  paranormal: 'Paranormal',
  duskmourn: 'Paranormal',
  draconic: 'Draconic',
  tarkir: 'Draconic',
  stellarsights: ['Stellar Sights', 'Poster Stellar Sights'],
  elemental: 'Elemental',
  fable: 'Fable',
  lorwyn: 'Fable',
  circuits: 'Circuits',
  poster: 'Poster',
  movie: 'Poster',
  comic: 'Comic',
  gamecover: 'Game Cover',
  bookcover: 'Book Cover',
  cover: ['Game Cover', 'Book Cover'],
  album: 'Album',
};

export const filterCardFrame: cardStringFilter = Object.assign(
  function (this: cardStringFilter, value1: HCCard.Any, operator: looseOpType, value2: string) {
    const actualOp = getActualOp(this, operator);
    if (!(value2 in toCardFrame)) {
      return false;
    }
    return shareOp(
      actualOp,
      [...value1.toFaces().flatMap(e => e.frame ?? []), ...(value1.frame ?? [])],
      toCardFrame[value2]
    );
  },
  { defaultOp: '=' as opType }
);
export const filterFrameEffect: cardStringFilter = Object.assign(
  function (this: cardStringFilter, value1: HCCard.Any, operator: looseOpType, value2: string) {
    const actualOp = getActualOp(this, operator);
    if (!(value2 in toFrameEffect)) {
      return false;
    }
    return shareOp(
      actualOp,
      [...value1.toFaces().flatMap(e => e.frame_effects ?? []), ...(value1.frame_effects ?? [])],
      toFrameEffect[value2]
    );
  },
  { defaultOp: '=' as opType }
);

export const filterFrame: cardStringFilter = Object.assign(
  function (this: cardStringFilter, value1: HCCard.Any, operator: looseOpType, value2: string) {
    const actualOp = getActualOp(this, operator);
    return filterCardFrame(value1, actualOp, value2) || filterFrameEffect(value1, actualOp, value2);
  },
  { defaultOp: '=' as opType }
);

export const filterShowcase: cardStringFilter = Object.assign(
  function (this: cardStringFilter, value1: HCCard.Any, operator: looseOpType, value2: string) {
    const actualOp = getActualOp(this, operator);
    if (!(value2 in toShowcaseFrame && value1.tag_notes?.['showcase-frame'])) {
      return false;
    }
    return shareOp(
      actualOp,
      value1.tag_notes['showcase-frame'].split(', '),
      toShowcaseFrame[value2]
    );
  },
  { defaultOp: '=' as opType }
);
