import { filterInterface } from './makerTypes';

/**
 * A filter node
 */
export type FilterNode =
  | { type: 'filter'; filter: filterInterface }
  | { type: 'not'; child: FilterNode }
  | { type: 'related'; child: FilterNode }
  | { type: 'and'; children: FilterNode[] }
  | { type: 'or'; children: FilterNode[] };

export const filterNames = [
  'id',
  'oracleid',
  'kind',
  'name',
  'set',
  'block',
  'group',
  'settype',
  'number',
  'layout',
  'facelayout',
  'anylayout',
  'mana',
  'manavalue',
  'supertype',
  'cardtype',
  'subtype',
  'type',
  'oracle',
  'flavor',
  'lore',
  'power',
  'toughness',
  'pt',
  'loyalty',
  'defense',
  'keyword',
  'legal',
  'notlegal',
  'banned',
  'creator',
  'artist',
  'artistnote',
  'ruling',
  'watermark',
  'border',
  'cardframe',
  'frameeffect',
  'frame',
  'showcase',
  'tag',
  'tagnote',
  'is',
  'has',
  'isrelated',
  'hasrelated',
  'include',
  'invalid',
  'invalidsort',
  'invalidkeyword',
  'invalidcolor',
] as const;
export type filterNameType = (typeof filterNames)[number];
export const isFilterName = (value: any): value is filterNameType => filterNames.includes(value);

export const equivFilterNames: Record<string, filterNameType> = {
  cardid: 'id',
  hcid: 'id',
  oid: 'oracleid',
  oi: 'oracleid',
  k: 'kind',
  n: 'name',
  s: 'set',
  b: 'block',
  g: 'group',
  st: 'settype',
  cube: 'settype',
  cn: 'number',
  collector: 'number',
  collectornumber: 'number',
  cardlayout: 'layout',
  fl: 'facelayout',
  al: 'anylayout',
  m: 'mana',
  cost: 'mana',
  manacost: 'mana',
  mv: 'manavalue',
  cmc: 'manavalue',
  t: 'type',
  super: 'supertype',
  supert: 'supertype',
  ct: 'cardtype',
  ctype: 'cardtype',
  sub: 'subtype',
  subt: 'subtype',
  o: 'oracle',
  text: 'oracle',
  oracletext: 'oracle',
  rules: 'oracle',
  rulestext: 'oracle',
  ft: 'flavor',
  flavortext: 'flavor',
  pow: 'power',
  tou: 'toughness',
  powtou: 'pt',
  tough: 'toughness',
  loy: 'loyalty',
  def: 'defense',
  kw: 'keyword',
  keywords: 'keyword',
  f: 'legal',
  format: 'legal',
  creators: 'creator',
  a: 'artist',
  artists: 'artist',
  an: 'artistnote',
  anote: 'artistnote',
  ans: 'artistnote',
  anotes: 'artistnote',
  artistn: 'artistnote',
  artistns: 'artistnote',
  artistnotes: 'artistnote',
  rulings: 'ruling',
  bordercolor: 'border',
  wm: 'watermark',
  watermarks: 'watermark',
  frameffects: 'frameeffect',
  frameffect: 'frameeffect',
  frameeffects: 'frameeffect',
  fe: 'frameeffect',
  show: 'showcase',
  sc: 'showcase',
  otag: 'tag',
  oracletag: 'tag',
  function: 'tag',
  tn: 'tagnote',
  tnote: 'tagnote',
  tns: 'tagnote',
  tnotes: 'tagnote',
  tagn: 'tagnote',
  tagns: 'tagnote',
  tagnotes: 'tagnote',
  ir: 'isrelated',
  isrel: 'isrelated',
  isrels: 'isrelated',
  isrelateds: 'isrelated',
  hr: 'hasrelated',
  rel: 'hasrelated',
  rels: 'hasrelated',
  hasrel: 'hasrelated',
  hasrels: 'hasrelated',
  related: 'hasrelated',
  relateds: 'hasrelated',
  hasrelateds: 'hasrelated',
  sort: 'invalidsort',
  order: 'invalidsort',
  dir: 'invalidsort',
  direction: 'invalidsort',
};
export const toFilterName = (value: string): filterNameType | undefined =>
  equivFilterNames[value] ?? (isFilterName(value) ? value : undefined);

const colorFilterNames = [
  'color',
  'indicator',
  'identity',
  'hybrid',
  'misccolor',
  'miscindicator',
  'miscidentity',
  'mischybrid',
] as const;
export type colorFilterNameType = (typeof colorFilterNames)[number];
export const isColorFilterName = (value: any): value is colorFilterNameType =>
  colorFilterNames.includes(value);
export const equivColorFilterNames: Record<string, colorFilterNameType> = {
  c: 'color',
  colors: 'color',
  colorindicator: 'indicator',
  ci: 'identity',
  cidentity: 'identity',
  colorid: 'identity',
  cid: 'identity',
  hi: 'hybrid',
  hci: 'hybrid',
  hid: 'hybrid',
  hcid: 'hybrid',
  hybridid: 'hybrid',
  hybrididentity: 'hybrid',
  hybridcoloridentity: 'hybrid',
  mc: 'misccolor',
  mcolors: 'misccolor',
  mcolor: 'misccolor',
  mcolorindicator: 'miscindicator',
  mci: 'miscidentity',
  mcidentity: 'miscidentity',
  mcolorid: 'miscidentity',
  mcid: 'miscidentity',
  mhi: 'mischybrid',
  mhci: 'mischybrid',
  mhid: 'mischybrid',
  mhcid: 'mischybrid',
  mhybridid: 'mischybrid',
  mhybrididentity: 'mischybrid',
  mhybridcoloridentity: 'mischybrid',
  miscc: 'misccolor',
  misccolors: 'misccolor',
  misccolorindicator: 'miscindicator',
  miscci: 'miscidentity',
  misccidentity: 'miscidentity',
  misccolorid: 'miscidentity',
  misccid: 'miscidentity',
  mischi: 'mischybrid',
  mischci: 'mischybrid',
  mischid: 'mischybrid',
  mischcid: 'mischybrid',
  mischybridid: 'mischybrid',
  mischybrididentity: 'mischybrid',
  mischybridcoloridentity: 'mischybrid',
};
export const toColorFilterName = (value: string): colorFilterNameType | undefined =>
  equivColorFilterNames[value] ?? (isColorFilterName(value) ? value : undefined);

const printsFilterNames = ['in', 'sets', 'prints'] as const;
export type printsFilterNameType = (typeof printsFilterNames)[number];
export const isPrintsFilterName = (value: any): value is printsFilterNameType =>
  printsFilterNames.includes(value);
export const equivPrintsFilterNames: Record<string, printsFilterNameType> = {};
export const toPrintsFilterName = (value: string): printsFilterNameType | undefined =>
  equivPrintsFilterNames[value] ?? (isPrintsFilterName(value) ? value : undefined);
export const invertedFilterNames: Record<string, filterNameType> = {
  not: 'is',
  exclude: 'include',
};
