import { DeckInfo } from "./types";

export const allDecks: DeckInfo[] = [
  {
    author: "Red",
    title: "Deck Designed for Legend Designed for Commander",
    text: "An Esper deck that uses its commander as an efficient draw engine and supports it with a variety of ETB synergies.",
    cards: {
      sideboard: [],
      main: [
        { count: 1, name: "Legend Designed for Commander" },
        { count: 1, name: "It That Enters" },
        { count: 1, name: "Kozilek, Drawn From Memory" },
        { count: 1, name: "Eldrazi Misplacer" },
        { count: 1, name: "Archmage of the Photocopier" },
        { count: 1, name: "Out of Inkling" },
        { count: 1, name: "It That Juggles" },
        { count: 1, name: "Bojuka Dog" },
        { count: 1, name: "ENTER // EXIT" },
        { count: 1, name: "Errata, the Silencer" },
        { count: 1, name: "Gentleman" },
        { count: 1, name: "Wailord" },
        { count: 1, name: "Doom Crow" },
        { count: 1, name: "I’m an original thought haver!" },
        { count: 1, name: "Regal Karakas" },
        { count: 1, name: "Obelisk Dollar Store" },
        { count: 1, name: "Call the Dermotaxi!" },
        { count: 1, name: "Spirited Companharmonicon" },
        { count: 1, name: "Big Rock" },
        { count: 1, name: "WotC Spy" },
        { count: 1, name: "Galaxy Brain Ugin" },
        { count: 1, name: "It Goes On // On // On // On" },
        { count: 1, name: "Oops I dropped all my bones" },
        { count: 1, name: "Sword of Warren Instigator" },
        { count: 1, name: "Death // Death" },
        { count: 1, name: "Photocopier" },
        {
          count: 1,
          name: "Learn // Work // Play // Get Along With Each Other",
        },
        { count: 1, name: "Loot That Body" },
        { count: 1, name: "Nabanharmonicon" },
        { count: 1, name: "Myr in Misery" },
        { count: 1, name: "Flicker into Oblivion" },
        { count: 1, name: "Emergency Wipe" },
        { count: 1, name: "My Ex's Reign of Lies // Portrait of My Ex" },
        { count: 1, name: "Isle of Man" },
        { count: 1, name: "Archetype of ()" },
        { count: 1, name: "🐟'RE ESC🐟" },
        { count: 1, name: "Magus of the Mox Pearl" },
        { count: 1, name: "Isamaru // Wasamaru" },
        { count: 1, name: "DiMyr Signet" },
        { count: 1, name: "The Thinker" },
        { count: 1, name: "Rapheap Scrounger" },
        { count: 1, name: "Breeding Pool a literal one" },
        { count: 1, name: "Rerelease" },
        { count: 1, name: "F*ckerwisp" },
        { count: 1, name: "Wrath of Salt" },
        { count: 1, name: "HC6: Banish to Minimum Wage" },
        { count: 1, name: "Luchador" },
        { count: 1, name: "Depression" },
        { count: 1, name: "Spell Slang" },
        { count: 1, name: "Skitter of Wizards" },
        { count: 1, name: "Command Phyrexian Tower" },
        { count: 1, name: "Convolving Wilds" },
        { count: 1, name: "Discount Mox Box" },
        { count: 1, name: "Weezer Signet" },
        { count: 1, name: "Mana Pride Shirt" },
        { count: 1, name: "ClueTM Game Board" },
        { count: 1, name: "!Macro Own" },
        { count: 1, name: "Convergent Evolution" },
        { count: 1, name: "Engineered Explosive Vegetation" },
        { count: 1, name: "Cursed Sliver Burial Ground" },
        { count: 1, name: "Zoning Violation" },
        { count: 1, name: "Evil Fucking Wizard Spell" },
        { count: 1, name: "Unnecessary Side Quest" },
        { count: 1, name: "Elkster's Trick" },
        { count: 1, name: "Inclusive Golem" },
        { count: 1, name: "Flummox" },
        { count: 1, name: "Minions: The Rise of Gru" },
        {
          count: 1,
          name: "ah my toaster has suffered a traumatic experience and has planeswalked to theros. // Toaster, on Theros",
        },
        { count: 1, name: "Tinybones' Wild Ride" },
        { count: 1, name: "Shitting With Not Blood Involved" },
        { count: 1, name: "Coastal Bluffs" },
        { count: 9, name: "Swamp" },
        { count: 9, name: "Plains" },
        { count: 11, name: "Island" },
      ],
    },
  },
  {
    title: "Goyf Control",
    text: `Arguably, Goyf Control is a deck. A collection of cards. It utilizes Pious Gravegoyf for beats and has a highly removal-based gameplan.
    
    Look at this paragraph break weee`,
    author: "i forgot",
    cards: {
      main: [
        { name: "Jund Supermarket", count: 4 },
        { name: "Pious Gravegoyf", count: 4 },
        { name: "Amogis, God of Sus", count: 2 },
        { name: "Dead on Arrival // Naturalize Magic", count: 4 },
        { name: "Rootin Tootin Tutor", count: 4 },
        { name: "Thrashing // Entering", count: 2 },
        { name: "Evolving Fabled Terramorphic Vista", count: 4 },
        { name: "Overgrown, Tomb of Yawgmoth", count: 1 },
        { name: "Forest", count: 2 },
        { name: "Mountain", count: 2 },
        { name: "Swamp", count: 1 },
        { name: `Thresh''s hole`, count: 1 },
        { name: "Wasteland Oasis", count: 4 },
        { name: "Altar of Broken Mechanics", count: 4 },
        { name: "Spooky Brainstorm", count: 4 },
        { name: "ThoughtSeas", count: 4 },
        { name: "Look For Trouble", count: 4 },
        { name: "Miasma // My Asthma", count: 4 },
        { name: "Cathartic Reunion But It's Dumb", count: 4 },
      ],
      sideboard: [
        {
          name: "Turn to Nature",
          count: 4,
        },
        {
          name: "Wolf Within",
          count: 4,
        },
        {
          name: "Spellcounter",
          count: 3,
        },
        {
          name: "Reject You Reality // Substitute My Own",
          count: 4,
        },
      ],
    },
  },
  {
    title: "UW Moderator",
    text: `Moderator seems to be the boogyman of the format. It plus a few counterspells is capable of locking out a good number of non-agro decks.`,
    author: "Glassbass",
    cards: {
      main: [
        { name: "Moderator", count: 4 },
        { name: "Thraben Rejector", count: 4 },
        { name: "Postmodernism", count: 4 },
        { name: "Shark", count: 3 },
        { name: "Flummox", count: 4 },
        { name: "Crucifact or Crucifixion", count: 4 },
        { name: "Mana Auction", count: 4 },
        { name: "Tax Audit", count: 4 },
        { name: "Walmart", count: 4 },
        { name: "Actual Tundra", count: 4 },
        { name: "Island GX", count: 1 },
        { name: `Polluted Δ`, count: 1 },
        { name: "Island", count: 8 },
        { name: "Plains", count: 4 },
        { name: "Island", count: 4 },
      ],
      sideboard: [
        {
          name: "The Prismatic Piper",
          count: 2,
        },
        {
          name: "Adventure",
          count: 4,
        },
        {
          name: "Counter-Fucking-Spell",
          count: 4,
        },
        {
          name: "The Scary Door",
          count: 3,
        },
        {
          name: "Divine Gambit but It's Fucking Stupid",
          count: 4,
        },
      ],
    },
  },
  {
    title: "Pieramid break",
    text: `This is a controlling deck that uses Pyramid Schemer's extort counters and Color Pie Break by tacking "drain one, tutor a basic land" onto every spell. That combined with cheap spells help allow for huge Dracjack turns.`,
    author: "Glassbass",
    cards: {
      main: [
        { name: "Pyramid Schemer", count: 4 },
        { name: "Sheoldred, Whispering One (hc)", count: 4 },
        { name: "Color Pie Break", count: 3 },
        { name: "White Counterspell", count: 4 },
        { name: "Stigmatize", count: 4 },
        { name: "whelming Splendor", count: 3 },
        { name: "Dracjack", count: 4 },
        { name: "Evolving Fabled Terramorphic Vista", count: 3 },
        { name: "Swamp", count: 6 },
        { name: "Plains", count: 9 },
        { name: "Moor of That Strange Oil", count: 2 },
        { name: "Snarlsnarlsnarl", count: 4 },
        { name: "Inquisition of Haktos the Unscarred", count: 4 },
        { name: "Dis Enchant", count: 4 },
      ],
      sideboard: [
        {
          name: "The Prismatic Piper",
          count: 2,
        },
        {
          name: "Abrupt Silence",
          count: 3,
        },
        {
          name: "Card Leak",
          count: 4,
        },
        {
          name: "Miasma // My Asthma",
          count: 4,
        },
        {
          name: "The Scary Door",
          count: 4,
        },
      ],
    },
  },
  {
    title: "Bant Moderator Tempo",
    text: `oh god more mod`,
    author: "Requiem",
    cards: {
      main: [
        { name: "Elephant Jump Scare", count: 4 },
        { name: "Moderator", count: 4 },
        { name: "Postmodernism", count: 4 },
        { name: "Thraben Rejector", count: 4 },
        { name: "Hush", count: 4 },
        { name: "Crucifact or Crucifixion", count: 4 },
        { name: "Into the Royal", count: 4 },
        { name: "Mana Auction", count: 4 },
        { name: "Tax Audit", count: 2 },
        { name: "Swamp (hc)", count: 4 },
        { name: "There Is No Bias In Color Balance", count: 4 },
        { name: "Tranquil Frontier", count: 2 },
        { name: "Tropical", count: 4 },
        { name: "Walmart", count: 4 },
        { name: "dRafter Demon's Used Car Lot", count: 4 },
        { name: "Ginkhole", count: 4 },
      ],
      sideboard: [
        {
          name: "Escalation Sage",
          count: 2,
        },
        {
          name: "Pithing Beeble",
          count: 2,
        },
        {
          name: "Scapegoat (HC3)",
          count: 1,
        },
        {
          name: "Stigmatize",
          count: 2,
        },
        {
          name: "Get Out of Jail Free",
          count: 4,
        },
        {
          name: "Tax Audit",
          count: 2,
        },
        {
          name: "Zoning Violation",
          count: 2,
        },
      ],
    },
  },
  {
    title: "Is this anything",
    text: `Goyf stuff. Uses Mob Farming Tower + hand dumping effects like Dumpstergoyf and One with that thing to generate treasure and get Very Motivated Skeletons into yard.`,
    author: "llllll",
    cards: {
      main: [
        { name: "Dumpstergoyf", count: 4 },
        { name: "Goyflebrand", count: 4 },
        { name: "Avatar of Jund", count: 3 },
        { name: "Very Motivated Skeleton", count: 3 },
        { name: "Cathartic Cathar", count: 2 },
        { name: "Wrenn and Six and Minsc and Boo", count: 2 },

        { name: "Goyf's Best Friend", count: 4 },
        { name: "SwAmp (Hellscube)", count: 4 },
        { name: "Jund Supermarket", count: 4 },
        { name: "Wasteland Oasis", count: 2 },
        { name: "Elder Dragon Highland", count: 2 },
        { name: "Grovergrown Tomb", count: 2 },
        { name: "Blood Crypt (Hellscube)", count: 2 },
        { name: "The Haunted Mansion", count: 2 },
        { name: "Groff Bayou", count: 2 },
        {
          name: "Time-Worn Jund Deckbox // Time-Worn Bloodbraid Elf",
          count: 2,
        },
        { name: "Assassin’s Participation Trophy", count: 3 },
        { name: "One with That Thing", count: 2 },
        { name: "Sponsored Expedite", count: 3 },
        { name: "Mob Farming Tower", count: 4 },
        { name: "Mining", count: 2 },
        { name: "Bad Nauseum", count: 2 },
      ],
      sideboard: [
        {
          name: "Grounter Spell",
          count: 4,
        },
        {
          name: "Thrashing // Entering",
          count: 4,
        },
        {
          name: "Dead on Arrival // Naturalize Magic",
          count: 3,
        },
        {
          name: "Nosy Intruder",
          count: 4,
        },
      ],
    },
  },
];
